# Generated by Django 2.1 on 2018-08-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
